### ISSUE TITLE
On iphone fonts are very long to load

### ISSUE THREAD

**Issue by javamind** [mixitconf/cesar#107]
![image](https://cloud.githubusercontent.com/assets/1812822/11242961/7f070068-8e05-11e5-80c6-44c8ee2ce3cb.png)

**Comment by cappert** [comment]
it's a known quirk on Safari, it doesn't show text until it's fully painted and the font is loaded.

**Comment by javamind** [comment]
A first fix is to limit the fonts loaded for the text
In a second time we will see for the font used for icons

**Comment by javamind** [comment]
Good article on icon fonts http://blog.cloudfour.com/seriously-dont-use-icon-fonts/
