### ISSUE TITLE
Registration with login: a key icon without tooltip is not very user-friendly as submit button

### ISSUE THREAD

**Issue by clacote** [mixitconf/cesar#118]
Current registration with login page: 
![image](https://cloud.githubusercontent.com/assets/750715/11361005/0c6aecc0-928a-11e5-8507-d8993c754f32.png)

I think that using a key icon, left-aligned, without any text, is not very user-friendly as a submit button: it takes time to understand you have to clic on that key to submit.

**Comment by javamind** [comment]
We can add behavior on buttons (a visual effect) and you're right a tooltip
