### ISSUE TITLE
A user should be able to see only his proposals

### ISSUE THREAD

**Issue by javamind** [mixitconf/cesar#204]

**Comment by mpetitdant** [comment]
It is not the case ?

**Comment by javamind** [comment]
No the text is not good. It would be a good thing that everybody can vote for all the session. You are the votes of the public with a percentage of 0.4 and a staff vote with a percentage of 0.6... 
It's just an idea and you can see a similar mechanism in Confoo in Montreal

**Comment by mpetitdant** [comment]
I think you mistake this issue with that one :
https://github.com/mix-it/cesar/issues/218 ?

**Comment by javamind** [comment]
No #218 <https://github.com/mix-it/cesar/issues/218>  is for the vote
during the event
I'd like to purpose a public vote for the CFP

2016-02-29 22:22 GMT+01:00 Mathieu Petitdant <notifications@github.com>:

> I think you mistake this issue with that one :
> https://github.com/mix-it/cesar/issues/218 ?
>
> On Mon, Feb 29, 2016 at 10:20 PM, Guillaume EHRET <
> notifications@github.com>
> wrote:
>
> > No the text is not good. It would be a good thing that everybody can vote
> > for all the session. You are the votes of the public with a percentage of
> > 0.4 and a staff vote with a percentage of 0.6...
> > It's just an idea and you can see a similar mechanism in Confoo in
> > Montreal
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/mix-it/cesar/issues/204#issuecomment-190401890>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mix-it/cesar/issues/204#issuecomment-190402337>.
>



-- 
*Guillaume EHRET*
*Conseil et développement*
*https://www.dev-mind.fr/ <http://www.dev-mind.fr/>*
Twitter <https://twitter.com/guillaumeehret> - Linkedin
<https://www.linkedin.com/in/guehret> - Mix-IT Conference staff
<https://www.mix-it.fr/>
