### ISSUE TITLE
Sponsor: lte them handle their logos

### ISSUE THREAD

**Issue by mpetitdant** [mixitconf/cesar#288]

**Comment by javamind** [comment]
We need to control the size and the quality. Maybe we can ask them to use only svg with a size < 15Ko or 20Ko

**Comment by clacote** [comment]
You'll loose 75% of sponsors by requiring SVG only.

**Comment by javamind** [comment]
So It's better to handle their logos for them to control the size, no ?

**Comment by clacote** [comment]
I would they it's better to have them manage their logo, as soon as any too big logo won't break the layout (be sure to define `max-height` and/or `max-width`). A shitty quality would be their problem.

**Comment by javamind** [comment]
The most important thing is the size. Example on home page 

![image](https://cloud.githubusercontent.com/assets/1812822/14019790/b746897a-f1d4-11e5-8ada-9929aa675aa5.png)

**Comment by clacote** [comment]
You're free to implement it safely by re-encoding their provided logo on upload! :)
